### ISSUE TITLE
Manage history feature

### ISSUE THREAD

**Issue by yaroslavyaroslav** [yaroslavyaroslav/OpenAI-sublime-text#12]
There's should be a way to manage chat histories.

As for now there's just a single history instance. But it would be really convenient if user could store several histories and be able to switches them by a command.

**Comment by dujas** [comment]
Hi 
how can I just open the history chat? For example I send a new message then I get the response which allows me to see the history as well. But how can I just reopen that panel to just view the history? Thank you

**Comment by yaroslavyaroslav** [comment]
@dujas Hi, there's a few ways to achieve that:
1. Firstly you can do it by right click on the very low left Sublime Text corner with a right click, then all opened panel list would appears, where you can chose OpenAI one.
2. There was a bug within the code, so the `OpenAI: Refresh Chat` command didn't worked. It is fixed in 2.0.3, which should become available for updating within several hours.
3. You can set a binding for that by adding an appropriate key to your `Key Bindings` file like the follow.

```json
{
"keys": [
    "super+shift+;"
],
"command": "show_panel",
"args": {
    "panel": "output.OpenAI"
}
```

**Comment by dujas** [comment]
@yaroslavyaroslav thanks a lot! I was able to open the panel list with a right click and then choose the OpenAI panel.
I wasn't able to set a key binding for that. I've tried with different keys combination as well but still it isn't working. I am using build 4143 under Ubuntu 22. 
I am looking forward for 2.0.3

**Comment by yaroslavyaroslav** [comment]
@dujas Sorry, but I didn't tested it on anything but macOS. Anyway, if you have enough effort to perform broad testing this plug-in on Linux I'll be happy to consider those issues when I'll have enough time though.
