### ISSUE TITLE
Fix output panel scrolling

### ISSUE THREAD

**Issue by yaroslavyaroslav** [yaroslavyaroslav/OpenAI-sublime-text#14]
Now output panel scroll offset is a hardcoded value. It should rather be a value that point out to the last `## Answer` line, this could be reached though pretty complex logic though.

**Comment by dujas** [comment]
Hi,
I don't know if this is related but the output is truncated for large answers.

**Comment by yaroslavyaroslav** [comment]
The error would change its behavior in 2.1.0. Since SSE to a chat functionality would be added in that release output panel scrolling will be following the latest batch of tokens model would present.

I'm facing disability of scrolling during such streaming and rare but persistent scroll glitching behavior.
