### ISSUE TITLE
Installation Guide Missing 

### ISSUE THREAD

**Issue by sbhadade** [yaroslavyaroslav/OpenAI-sublime-text#20]
The Installation Guide Missing  ? Can some guide how to install it ?

**Comment by yaroslavyaroslav** [comment]
Thank you for your concern. 

Wold you consider to add that to current readme by yourself?

I mean it's a really good point, but I can't promise that I'd implement it soonish.

**Comment by kaklik** [comment]
> The Installation Guide Missing ? Can some guide how to install it ?

I had the same problem. Finally I found the installation is two step. The first step is to [install the package control](https://packagecontrol.io/installation)

The second step is to use package control to search and install the OpenAI plugin. (That could be done from package search)

**Comment by yaroslavyaroslav** [comment]
@kaklik I'm really curious how did you get to know about this plug-in before you've got package control installed?

I just thought that searching there is the main and only way how ppl finds it, and now it obvious that there's another way.

**Comment by kaklik** [comment]
> @kaklik I'm really curious how did you get to know about this plug-in before you've got package control installed?
> 
> I just thought that searching there is the main and only way how ppl finds it, and now it obvious that there's another way.

I had specifically searched for a GPT-4 plugin for text editor on the web.

**Comment by yaroslavyaroslav** [comment]
@kaklik So do I get you right that it's the plugin was the reason why you've installed Sublime Text or is it that you've used it before but just haven't any plugin installed?
