### ISSUE TITLE
Key Bindings can not be set

### ISSUE THREAD

**Issue by eusonlito** [yaroslavyaroslav/OpenAI-sublime-text#3]
When you click the `Preferences` > `Package Settings` > `OpenAI completion` > `Key Bindings` menu option the console show the error:

```
error: The settings file "res://Packages/openAI/Default.sublime-keymap" could not be opened
```

You have defined the key bindings base file here:

https://github.com/yaroslavyaroslav/OpenAI-sublime-text/blob/develop/Main.sublime-menu#L27

But the `base_file` `Default.sublime-keymap` not exists in the repository.

**Comment by rchl** [comment]
Also, after adding that file, I would suggest to include a suggested key binding there but commented out. Then the user can easily copy it over to user key bindings and enabled. Another reason this is useful because user doesn't know what command and arguments to use for the key binding since it's not documented. So maybe include all three different key bindings with different `mode` arguments.

**Comment by yaroslavyaroslav** [comment]
It was, since it's working for me, but I guess it has gone somewhere within package publication process. I'll move it back shortly, and punch update.

**Comment by yaroslavyaroslav** [comment]
It could worth it. I'm not promise to provide full command list, but I'll provide the bare minimum for sure.

**Comment by raineorshine** [comment]
I ran into the same error with v1.1.2. I had to manually add `Packages/User/openAI.sublime-settings`. It still gives the error when I try to access the Settings through the menu, but at least it reads my API key.

**Comment by yaroslavyaroslav** [comment]
@raineorshine I see that it's different one. The original was not about `sublime-settings`, but about `sublime-keymap` which was really dropped from the project of the review stage. 

Could you please open new issue, and provide some details, like: Sublime version, OS version, error log if any.

**Comment by raineorshine** [comment]
I get the same error for both settings and keymap. I'll open an another issue when I'm back at my computer!
