### ISSUE TITLE
Request to Integrate Azure's Version of the OpenAI API

### ISSUE THREAD

**Issue by yigitkonur** [yaroslavyaroslav/OpenAI-sublime-text#30]
This API is no longer provided solely by OpenAI, Azure is now offering the same service. The implementation is not complicated at all, it's enough for you to create a field in the settings section for us to define the `baseURL`. Afterwards, everyone can easily integrate it. There are minor differences on the API side, but if you want to implement it, I don't think it will be a huge task. Thank you so much for your support, Yaroslav!

**Comment by yaroslavyaroslav** [comment]
Thank you for such kind words, I really appreciate it! Also that's a great news that OpenAI services are available now somewhere else that just their own hosting. 

Could you please provide me with a link to a proper azure man page about their implementation specific?

**Comment by yaroslavyaroslav** [comment]
@yigitkonur could you please try is it working with azure on 3.2.0 with its latest custom url feature?

**Comment by yaroslavyaroslav** [comment]
I consider this as implemented in #40. Please reopen it if case it's not.
