### ISSUE TITLE
How to use with ollama

### ISSUE THREAD

**Issue by reagle** [yaroslavyaroslav/OpenAI-sublime-text#48]
1. I am running llama3 in the terminal.
2. I have `openAI.sublime-settings` as:
```
// Settings in here override those in "OpenAI completion/openAI.sublime-settings"
{
	"url": "http://localhost:11434",
	"token": "sk-your-token",
	"model": "llama3",
}
```

3. but when I invoke new message, whatever I type in the "Question:" bottom panel returns: "OpenAI error
model 'gpt-4-0613' not found, try pulling it first".

**Comment by yaroslavyaroslav** [comment]
Seems like you're running "OpenAI: New Message" right from the start instead of to run "OpenAI: Chat Model Select" first to select a model from the list.

**Comment by yaroslavyaroslav** [comment]
https://github.com/yaroslavyaroslav/OpenAI-sublime-text#ai-assistance-use-case please check this part of readme for detailed instructions.

**Comment by reagle** [comment]
I did try that, but didn't see llama3 in the menu. (I can scroll down a bit further, but it's not there.) I thought since I specified `"model": "llama3"` it would be in the menu or be set in any case.

**Comment by reagle** [comment]
<img width="664" alt="SCR-20240502-sepz" src="https://github.com/yaroslavyaroslav/OpenAI-sublime-text/assets/596814/0c66f562-a3b2-4756-90aa-ae02f2c94960">

**Comment by yaroslavyaroslav** [comment]
Yeah, now I see.

You have a few issues within your config. Here's the correct example:

```json
{
    "url": "http://localhost:11434",
    "token": "sk-your-token",
    "status_hint": [
        "name",
        "prompt_mode",
        "chat_model"
    ],
    "assistants": [
        {
            "name": "Local llama assistant",
            "model": "llama3",
            "assistant_role": "You are a senior code assistant",
            "prompt_mode": "panel"
        }
    ]
}
```

Please pay attention that now the `"assistants"` array appears within the setup and assistant related settings were moved there. The second thing to consider is that there are 4 required settings to make things work (like to add the next to it predefined assistant), they are `"name"`, `"model"`, `"assistant_role"`, "prompt_mode".

I'd recommend to read comments in settings when you'll have time for obtaining more in depth knowledge of how this thing work https://github.com/yaroslavyaroslav/OpenAI-sublime-text/blob/master/openAI.sublime-settings#L47-L73

**Comment by reagle** [comment]
BTW: Here was the error:

```
...
RuntimeError: unable to instantiate 'OpenAI completion.openai_panel.OpenaiPanelCommand'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python38/sublime_plugin.py", line 535, in create_window_commands
    o = cls(window)
  File "/Users/reagle/Library/Application Support/Sublime Text/Installed Packages/OpenAI completion.sublime-package/openai_panel.py", line 20, in __init__
    self.load_assistants()
  File "/Users/reagle/Library/Application Support/Sublime Text/Installed Packages/OpenAI completion.sublime-package/openai_panel.py", line 26, in load_assistants
    self.assistants: List[AssistantSettings] = [
  File "/Users/reagle/Library/Application Support/Sublime Text/Installed Packages/OpenAI completion.sublime-package/openai_panel.py", line 27, in <listcomp>
    AssistantSettings(**{**DEFAULT_ASSISTANT_SETTINGS, **assistant})
TypeError: __init__() got an unexpected keyword argument 'model'

The above exception was the direct cause of the following exception:

RuntimeError: unable to instantiate 'OpenAI completion.openai_panel.OpenaiPanelCommand'
Empty file I belive
Empty file I belive
...
```

**Comment by yaroslavyaroslav** [comment]
Yep, there was a mistake in the provided snipped above fixed it.
