### ISSUE TITLE
Option to strip markdown from responses

### ISSUE THREAD

**Issue by IPWright83** [yaroslavyaroslav/OpenAI-sublime-text#53]
I've been having a play with this and I'm struggling to get models to respond without random messages like "sure", explanations and MDX code escaping, despite what I try.

Would it be possible to add an option, configurable for each assistant that would basically strip out anything markdown, except for actual written code? Then examples like this would just use the inner code for replacement etc.

![image](https://github.com/yaroslavyaroslav/OpenAI-sublime-text/assets/1374775/68889ac6-fde6-4d78-aba1-96e28af8ac4f)

**Comment by yaroslavyaroslav** [comment]
Here's the related comment in discussion about that.https://github.com/yaroslavyaroslav/OpenAI-sublime-text/discussions/52#discussioncomment-9898516 I believe that in some of the next coding session with this plugin I'll make in buffer modes a bit more usable, but not promises.

**Comment by yaroslavyaroslav** [comment]
As it were discussed in the discussion (sic) above it's llm related bug, thus closing the issue.
