### ISSUE TITLE
Open panel immediately on submission 

### ISSUE THREAD

**Issue by IPWright83** [yaroslavyaroslav/OpenAI-sublime-text#54]
When using a chat panel, I think it'd be useful if the panel were to open immediately upon submission, rather than wait for the streaming response. This gives a better impression of success and feedback that the question has been submitted.

**Comment by yaroslavyaroslav** [comment]
> This gives a better impression of success and feedback that the question has been submitted.

I'd disagree with that claim. I think that it wills be direct opposite honestly. Until a server responded with 200 and started to stream the prompt back it's undefined whether the request succeeded or not, so popping up the output panel beforehand is too hasty actually

**Comment by IPWright83** [comment]
Ok fair enough, I've also had a couple of times where chat output appears in the editor rather than the panel. Have you seen that before?

**Comment by yaroslavyaroslav** [comment]
In a separate tab or in an active one?

If the case is the latter it could be this bug #51 if your default assistant set to append/edit/insert behavior.

**Comment by yaroslavyaroslav** [comment]
Closed as stalled
