### ISSUE TITLE
Setting 'max_tokens' and 'max_completion_tokens' at the same time is not supported

### ISSUE THREAD

**Issue by maunovaha** [yaroslavyaroslav/OpenAI-sublime-text#65]
Hi,

I keep getting this error: "Setting 'max_tokens' and 'max_completion_tokens' at the same time is not supported." when I try to use the plugin.

I have installed the package, and placed the OpenAI API access token under the user settings:

```
{
    // Your openAI token
    "token": "xxxxxxx"
}
```

Am I doing something wrong? I have tried to set "max_tokens" or "max_completion_tokens" to values like "" or null, but it doesn't make any difference, the error persists and I cannot use the plugin.

**Comment by yaroslavyaroslav** [comment]
Nope it should works that way, so it could be a bug on my side, could you please provide one more time exact config on which it reproduces (with faked apikey certainly)?

**Comment by yaroslavyaroslav** [comment]
Yeah, I got it. It's the default config is broken for OpenAI currently. 

You have to copy paste the whole assistants chunk from within to your user cfg and to disable either max_tokens or max_completion_tokens in the very first assistant settings. 

Or you can wait for a few hours till I release the patch.
