### ISSUE TITLE
Advertisement disabling

### ISSUE THREAD

**Issue by klonuo** [yaroslavyaroslav/OpenAI-sublime-text#67]
Why are you doing this instead focusing on right challenges; so lame...

**Comment by yaroslavyaroslav** [comment]
I'm not observing here any constructive request or question, sorry. 

I'm closing this.

**Comment by klonuo** [comment]
I can't meet you under the bridge, was trying to be constructive

**Comment by yaroslavyaroslav** [comment]
If you have the direct question about the plugin or its features feel free to ask. But I haven't seen it yet.

**Comment by klonuo** [comment]
I can sure, please allow serverless access to working models on 🤗

https://huggingface.co/docs/api-inference/en/index

**Comment by yaroslavyaroslav** [comment]
At a glance [this](https://huggingface.co/docs/api-inference/en/tasks/chat-completion#request) API looks similar to OpenAI one, so it should work already. Have you tried to set up assistant with hf gateway? Is there any errors throwing from server?

**Comment by klonuo** [comment]
Serverless it's not compatible with OpenAI scheme, just for their endpoint which are paid. I'll try to handle without promising
