### ISSUE TITLE
max_tokens is not enforced correctly

### ISSUE THREAD

**Issue by paschembri** [yaroslavyaroslav/OpenAI-sublime-text#8]
Token count is currently based on the length of the selection (`if (self.settings.get("max_tokens") + len(self.text)) > 4000:`).

However, OpenAI models are using `GPT2Tokenizer` which leads to a more accurate token count.

As of now I didn't find an *easy* way to include 3rd-party deps for a sublime package (the python package `transformers` should be used).

What do you think about adding a setting enabling the user to override the 4000 limit ? (Happy to provide a PR).

**Comment by yaroslavyaroslav** [comment]
Thank you for your proposal. There's an easy way to add a 3rd party dependency actually. 

It should be added [this way](https://github.com/sublimelsp/LSP/blob/main/dependencies.json). Unlikely I'd found that only after I did implement it within stdlib boundaries.

Anyway, I'd rather prefer to not add `transformers` package if it's more than let's say 10mb with all its dependencies. This plugin is pretty light and straightforward so far, and I'd like to keep it that way.

So here's my proposal towards to you: if the `transformers` package are not so big one -- you are very welcome to use in in your PR, and if it's not please consider to made tokens count less precise p, but without such package.

**Comment by paschembri** [comment]
I’ll look into it but I know the transformers package does magic stuff (like downloading vocab files…)

I think extracting a basic rule may be simpler…

**Comment by yaroslavyaroslav** [comment]
I've found the library that is suggested for counting tokens locally. Have to check it's size before include it in project anyway. 

https://github.com/openai/tiktoken

**Comment by yaroslavyaroslav** [comment]
https://github.com/wbond/package_control_channel/blob/master/repository/dependencies.json

It appears, that only packages from within this list are available for being dependencies.

**Comment by paschembri** [comment]
I managed to get a tiktoken server running locally (this is overkill but fits my need)

Small plugin here : https://github.com/paschembri/sublime-plugin-maker/tree/main/examples/Tiktoken-Counter
Tiktoken server here : https://github.com/paschembri/tiktoken-server

**Comment by yaroslavyaroslav** [comment]
@paschembri guess it could be toggled feature. Like if a user wants it so hard to install smth in addition to a plugin — he or she could have it, but by destiny it would be disabled. 

And just curious, why do you need it that much? Cold you please elaborate your flow?

**Comment by yaroslavyaroslav** [comment]
@paschembri am I get you right, that your mostly working with an edged scale text corpuses, like the one that's pretty close to the upper bound of a model? 

I mean, from my side I'm hitting such limit of a single prompt close to never on both `gpt-4` and `got-turbo-32k` even though I'm using pretty big code chunks to passing in in my daily workflow. So I still trying to find the answer, why does such accuracy is necessary? Even taking in account an oncoming error, it shouldn't be that large in a scale under 10k tokens to affects user flow in a dramatic way, if we'd just presume that each token ~ 4 chars. So what do I missing?

P.S: I'm not arguing in any way here. Just trying to dig deep enough in your case.

**Comment by yaroslavyaroslav** [comment]
> large prompt => small expected output : this is the worst case scenario where I want to be able to tell how much token is the prompt

In the very last release (2.1.0) this case is covered in a straightforward way: if the sum of prompt and `max_token` values is exceeds a model limit the OpenAI gateway throws an error with the exact numbers of both exact prompt tokens amount that have been passed and `max_tokens`. Before the last release i've just silenced that message, but now I passthrough to a user by sublime error message popup and the sublime logs printout. Have you tried that already, does it met your needs?

Anyway I sill believe that it's a good feature to count it at least in some approximate way local, and maybe it's worth a shot to add your even more precise solution as an optional one. But before doing latter I have to figure out its use cases to design a proper solution.

**Comment by vty21** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
eikodev, @ngoluuduythai, @p0p3yee, @al-sabr, @akru, @icodezjb, @canewsin, @johnrjj, @pmespresso, @brandawsd, @alcuadrado, @amirgamil, @cmars, @junhoyeo, @Ramyromel, @DaviRain-Su, @anylzer, @AllanM007, @0xys, @jhscheer, @engelin, @bjornwgnr, @juniuszhou, @hkxiaoyu118, @bwhour, @hzqd, @Volland, @thorpkuhn, @xlc, @llifezou, @KQisz, @DukeCaesar, @scheuclu, @waheya, @NukeManDan, @BlockchainWatchDog, @Moliholy, @red-0ne, @kartset, @elicharlese, @tututu-patch, @soc1c, @FISHers6, @oo7ph, @prm3theus, @vanchi198, @Lz1y, @greyireland, @robertleifke, @h4x3rotab
