### ISSUE TITLE
Never tested with Ollama

### ISSUE THREAD

**Issue by dmilith** [yaroslavyaroslav/OpenAI-sublime-text#94]
No matter what I change, no matter if I drop all ChatGPT related settings and assistants, or which url I set, it queries the ChatGPT only. Nothing else. If you support Llama, then at least test it, please.

**Comment by yaroslavyaroslav** [comment]
I encourage you to provide full details on how and what exactly did you changed. Coz it's definitely works with ollama for other folks #13

**Comment by dmilith** [comment]
Ok, based on that #57 I figured out it's about the value of "sk-your-token". If it's "" it will not work, even though I use local Llama3:8b. Thanks!
